import { ClockIcon, MapPinIcon, PhoneIcon } from "@heroicons/react/24/outline";
import Head from "next/head";

export default function Contact() {
    return (
        <div>
            <Head>
                <title>Loctech Portal | Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="lg:px-20 px-4 flex flex-col justify-center items-center my-20 gap-6">
                <h1 className="text-black text-[32px] font-medium">We&apos;re always eager to hear from you!</h1>
                <p className="text-[15px] font-light lg:w-1/2 text-center">Lorem ipsum dolor sit amet, consec tetur cing elit. Suspe ndisse suscorem ipsum dolor sit ametcipsum ipsumg consec tetur cing elitelit.</p>
                <div className="flex lg:flex-row flex-col lg:gap-32 gap-10 mt-10">
                    <div className="flex lg:flex-row flex-col lg:justify-start justify-center lg:items-start items-center gap-4">
                        <MapPinIcon className="w-8 h-8 text-violet-700" />
                        <div className="flex flex-col gap-6 lg:justify-start justify-center lg:items-start items-center">
                            <h1 className="text-[18px] font-medium">Address</h1>

                            <div className="font-light leading-relaxed lg:text-start text-center">
                                4A Etim Okpoyo Street,
                                <br />
                                Bridge Bus Stop,
                                <br />
                                Aba Road, Port Harcourt, Nigeria
                            </div>
                        </div>
                    </div>
                    <div className="flex lg:flex-row flex-col lg:justify-start justify-center lg:items-start items-center gap-4">
                        <PhoneIcon className="w-8 h-8 text-violet-700" />
                        <div className="flex flex-col gap-6">
                            <h1 className="text-[18px] font-medium">Contact</h1>
                            <div className="flex flex-col gap-3 font-light lg:justify-start justify-center lg:items-start items-center">
                                <span>Mobile: +2347038885466</span>
                                <span>Mail: customercare@loctechng.com</span>
                            </div>
                        </div>
                    </div>
                    <div className="flex lg:flex-row flex-col gap-4 lg:justify-start justify-center lg:items-start items-center">
                        <ClockIcon className="w-8 h-8 text-violet-700" />
                        <div className="flex flex-col gap-6 lg:justify-start justify-center lg:items-start items-center">
                            <h1 className="text-[18px] font-medium"> Hour of operation</h1>
                            <div className="font-light">Monday - Friday: 09:00 - 17:00</div>
                        </div>
                    </div>
                </div>
                <div>
                    <form className="max-w-3xl mt-10 flex flex-col gap-4">
                        <h1 className="font-medium text-[32px] text-center">Fill the form below so we can get to know you and your needs better.</h1>
                        <div className="grid lg:grid-cols-2 grid-flow-row gap-6">
                            <input
                                type="text"
                                placeholder="Your Name *"
                                className="px-4 py-4 lg:w-full bg-violet-50 focus:bg-white outline-none border border-transparent focus:border-violet-700 transition-colors duration-500 ease-in-out rounded-md"
                            />
                            <input
                                type="email"
                                placeholder="Your Email *"
                                className="px-4 py-4 lg:w-full bg-violet-50 focus:bg-white outline-none border border-transparent focus:border-violet-700 transition-colors duration-500 ease-in-out rounded-md"
                            />
                            <textarea
                                name=""
                                id=""
                                cols="30"
                                rows="5"
                                placeholder="Your Comment"
                                className="lg:col-span-3 px-4 py-3 bg-violet-50 focus:bg-white outline-none border border-transparent focus:border-violet-700 transition-colors duration-500 ease-in-out rounded-md"
                            />
                        </div>
                        <button
                            className="py-3 px-4 bg-violet-700 text-white rounded-md font-bold lg:w-40 hover:border hover:border-gray-200 hover:bg-white hover:text-violet-700 transition-colors duration-500 ease-in-out"
                        >
                            Submit
                        </button>
                    </form>
                </div>
            </div>
        </div>
    )
}